name: Alex Ortiz-Rosado 
description: Engineering Leader
meta_description: "Alex Ortiz-Rosado | Engineering Leader"
intro: "Technical leader in the startup and enterprise space who is passionate about culture, community, developer experience, performance, accessibility, and process improvement.
<br />
<br />
<a href='https://github.com/alexortizrosado'>Github</a> | <a href='https://linkedin.com/in/alexortizrosado'>LinkedIn</a> | <a href='/assets/alex-ortiz-rosado-resume.pdf'>Resume</a>

"

# aboutPage: true

# markdown: redcarpet
# highlighter: pygments

baseurl: /
domain_name: 'http://alexortizrosado.com'
google_analytics: 'UA-77007201-1'
disqus_shortname: 'alexortizrosado'

# Details for the RSS feed generator
url:            'http://alexortizrosado.com'
author:         'Alex Ortiz-Rosado'
authorTwitter:  'alexortizrosado'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
